src/FamilyTreeBundle/Entity/Changes.php
<?php

namespace FamilyTreeBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Changes
 *
 * @ORM\Table()
 * @ORM\Entity
 */
class Changes
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="author", type="string", length=255)
     */
    private $author;

    /**
     * @var string
     *
     * @ORM\Column(name="comment", type="text")
     */
    private $comment;
    
    /**
     * @var string
     *
     * @ORM\Column(name="region", type="text")
     */
    private $region;
	
	/**
     * @var string
     *
     * @ORM\Column(name="date", type="date")
     */
    private $pdate;

    /**
     * @ORM\OneToMany(targetEntity="FieldChange", mappedBy="changes", cascade={"remove","persist"})
     * @var ArrayCollection $changes
     */
    private $changes;

    /**
     * @ORM\ManyToOne(targetEntity="Person", inversedBy="changes")
     * @ORM\JoinColumn(name="person", referencedColumnName="id", nullable=true, onDelete="SET NULL" )
     */
    private $person;

    /**
     * Constructor
     */
    public function __construct($author = null, $comment = null, $region = null, $pdate = null, $person = null)
    {
        $this->author = $author;
        $this->comment = $comment;
        $this->region = $region;
        $this->pdate = $pdate;
		$this->person = $person;
        $this->changes = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set author
     *
     * @param string $author
     * @return Changes
     */
    public function setAuthor($author)
    {
        $this->author = $author;

        return $this;
    }

    /**
     * Get author
     *
     * @return string 
     */
    public function getAuthor()
    {
        return $this->author;
    }

    /**
     * Set comment
     *
     * @param string $comment
     * @return Changes
     */
    public function setComment($comment)
    {
        $this->comment = $comment;

        return $this;
    }

    /**
     * Get comment
     *
     * @return string 
     */
    public function getComment()
    {
        return $this->comment;
    }
	
	/**
     * Set pdate
     *
     * @param DateTime $pdate
     * @return Changes
     */
    public function setDate($pdate)
    {
        $this->pdate = $pdate;

        return $this;
    }

    /**
     * Get pdate
     *
     * @return DateTime 
     */
    public function getDate()
    {
        return $this->pdate;
    }

    /**
     * Add changes
     *
     * @param \FamilyTreeBundle\Entity\FieldChange $changes
     * @return Changes
     */
    public function addChange(\FamilyTreeBundle\Entity\FieldChange $changes)
    {
        $this->changes[] = $changes;

        return $this;
    }

    /**
     * Remove changes
     *
     * @param \FamilyTreeBundle\Entity\FieldChange $changes
     */
    public function removeChange(\FamilyTreeBundle\Entity\FieldChange $changes)
    {
        $this->changes->removeElement($changes);
    }

    /**
     * Get changes
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getChanges()
    {
        return $this->changes;
    }

    /**
     * Set person
     *
     * @param \FamilyTreeBundle\Entity\Person $person
     * @return Changes
     */
    public function setPerson(\FamilyTreeBundle\Entity\Person $person = null)
    {
        $this->person = $person;

        return $this;
    }

    /**
     * Get person
     *
     * @return \FamilyTreeBundle\Entity\Person 
     */
    public function getPerson()
    {
        return $this->person;
    }

    /**
     * Set pdate
     *
     * @param \DateTime $pdate
     * @return Changes
     */
    public function setPdate($pdate)
    {
        $this->pdate = $pdate;

        return $this;
    }

    /**
     * Get pdate
     *
     * @return \DateTime 
     */
    public function getPdate()
    {
        return $this->pdate;
    }

    /**
     * Set region
     *
     * @param string $region
     * @return Changes
     */
    public function setRegion($region)
    {
        $this->region = $region;

        return $this;
    }

    /**
     * Get region
     *
     * @return string 
     */
    public function getRegion()
    {
        return $this->region;
    }
}

src/FamilyTreeBundle/Entity/Person.php
<?php

namespace FamilyTreeBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Person
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="FamilyTreeBundle\Entity\Repository\PersonRepository")
 */
class Person
{
    public function returnDate()
    {
        return $this->birthYear;
    }

    public function getNames()
    {
        $lname = $this->lastName ? $this->lastName . ' ' : '';
        $fname = $this->firstName ? $this->firstName . ' ' : '';
        //.($this->birth||$this->death?'(':'').($this->birth?$this->birth->format('Y'):'unknown').($this->death ? ' - ':'').($this->death?$this->death->format('Y'):'unknown').($this->birth||$this->death?')':'')
        $fname = explode(" ", $fname);
        return $lname . $fname[0];
    }

    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="firstName", type="string", length=255)
     */
    private $firstName;

    /**
     * @var string
     *
     * @ORM\Column(name="lastName", type="string", length=255)
     */
    private $lastName;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="birth", type="date", nullable=true)
     */
    private $birth;

    /**
     * @var string
     *
     * @ORM\Column(name="birthYear", type="string")
     */
    private $birthYear;

    /**
     * @var string
     *
     * @ORM\Column(name="birthDate", type="string", nullable=true)
     */
    private $birthDate;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="death", type="date", nullable=true)
     */
    private $death;

    /**
     * @var string
     *
     * @ORM\Column(name="deathYear", type="string")
     */
    private $deathYear;

    /**
     * @var string
     *
     * @ORM\Column(name="deathDate", type="string", nullable=true)
     */
    private $deathDate;

    /**
     * @var string
     *
     * @ORM\Column(name="occupation", type="string", length=255, nullable=true)
     */
    private $occupation;


    /**
     * @var string
     *
     * @ORM\Column(name="birthPlace", type="string", length=255, nullable=true)
     */
    private $birthPlace;

    /**
     * @var string
     *
     * @ORM\Column(name="deathPlace", type="string", length=255, nullable=true)
     */
    private $deathPlace;

    /**
     * @var string
     *
     * @ORM\Column(name="note", type="text", nullable=true)
     */
    private $note;

    /**
     * @var string
     *
     * @ORM\Column(name="privateNote", type="text", nullable=true)
     */
    private $privateNote;

    /**
     * @var string
     * @ORM\ManyToOne(targetEntity="GalleryBundle\Entity\File")
     */
    private $avatarFile;


    /**
     * @ORM\Column(name="avatar_url", type="string", nullable=true)
     */
    private $avatarUrl;

    /**
     * @ORM\ManyToMany(targetEntity="Person", mappedBy="children", cascade={"persist"})
     * @ORM\OrderBy({"sex" = "DESC"})
     */
    private $parents;

    /**
     * @ORM\OneToMany(targetEntity="Marriage", mappedBy="person")
     */
    private $marriages;

    /**
     * @ORM\ManyToMany(targetEntity="Person", inversedBy="parents", cascade={"persist"})
     * @ORM\JoinTable(name="Children",
     * joinColumns={@ORM\JoinColumn(name="child", referencedColumnName="id")},
     * inverseJoinColumns={@ORM\JoinColumn(name="parent", referencedColumnName="id")}
     * )
     * @ORM\OrderBy({"birthYear" = "ASC"})
     */
    private $children;

    /**
     * @ORM\ManyToMany(targetEntity="Person", cascade={"persist"})
     * @ORM\JoinTable(name="Brotherhood",
     * joinColumns={@ORM\JoinColumn(name="person_1", referencedColumnName="id")},
     * inverseJoinColumns={@ORM\JoinColumn(name="person_2", referencedColumnName="id")}
     * )
     * @ORM\OrderBy({"birthYear" = "ASC"})
     */
    private $brotherhood;

    /**
     * @var boolean
     *
     * @ORM\Column(name="sex", type="boolean", nullable=true)
     */
    private $sex;

    /**
     * @var string
     *
     * @ORM\Column(name="nickname", type="string", length=255, nullable=true)
     */
    private $nickname;

    /**
     * @var string
     *
     * @ORM\Column(name="is_published", type="boolean", options={"default" = true})
     */
    private $isPublished;

    /**
     * @ORM\OneToMany(targetEntity="GalleryBundle\Entity\File", mappedBy="owner", cascade={"remove","persist"})
     */
    private $files;

    /**
     * @ORM\OneToMany(targetEntity="Changes", mappedBy="person", cascade={"remove","persist"})
     */
    private $changes;

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->marriages = new \Doctrine\Common\Collections\ArrayCollection();
        $this->children = new \Doctrine\Common\Collections\ArrayCollection();
        $this->parents = new \Doctrine\Common\Collections\ArrayCollection();
        $this->brotherhood = new \Doctrine\Common\Collections\ArrayCollection();
        $this->isPublished = true;
    }


    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set firstName
     *
     * @param string $firstName
     * @return Person
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Set firstName
     *
     * @param string $firstName
     * @return Person
     */
    public function setFirstName($firstName)
    {
        $this->firstName = strtolower($firstName);

        return $this;
    }

    /**
     * Get firstName
     *
     * @return string
     */
    public function getFirstName()
    {
        return $this->firstName;
    }

    /**
     * Set lastName
     *
     * @param string $lastName
     * @return Person
     */
    public function setLastName($lastName)
    {
        $this->lastName = strtolower($lastName);

        return $this;
    }

    /**
     * Get lastName
     *
     * @return string
     */
    public function getLastName()
    {
        return $this->lastName;
    }

    /**
     * Set birth
     *
     * @param \DateTime $birth
     * @return Person
     */
    public function setBirth($birth)
    {
        $this->birth = $birth;

        return $this;
    }

    /**
     * Get birth
     *
     * @return \DateTime
     */
    public function getBirth()
    {
        $year = $this->birthYear;
        $date = $this->birthDate;
        if ($date != "") {
            $date = $date . "/";
        }
        return $date . $year;
    }


    /**
     * Set birthAlt
     *
     * @param string $birthAlt
     * @return Person
     */
    public function setBirthAlt($birthAlt)
    {
        if (strlen($birthAlt) == 4) {
            $this->birthYear = $birthAlt;
            $this->birthDate = '';
        } elseif (strlen($birthAlt) == 10) {
            $delimeter = preg_replace("/[0-9\s]/", "", $birthAlt);
            $datearr = explode($delimeter[0], $birthAlt);
            $birthAlt = $datearr[2] . "-" . $datearr[1] . "-" . $datearr[0];
            $this->birthYear = $datearr[2];
            $this->birthDate = $datearr[0] . "/" . $datearr[1];
        } elseif (strlen($birthAlt) == 0) {
            $this->birthYear = '';
            $this->birthDate = '';
        }
        return $this;
    }

    /**
     * Set deathAlt
     *
     * @param string $deathAlt
     * @return Person
     */
    public function setDeathAlt($deathAlt)
    {

        if (strlen($deathAlt) == 4) {
            $this->deathYear = $deathAlt;
            $this->deathDate = '';

        } elseif (strlen($deathAlt) == 10) {
            $delimeter = preg_replace("/[0-9\s]/", "", $deathAlt);
            $datearr = explode($delimeter[0], $deathAlt);
            $deathAlt = $datearr[2] . "-" . $datearr[1] . "-" . $datearr[0];
            $this->deathYear = $datearr[2];
            $this->deathDate = $datearr[0] . "/" . $datearr[1];
        } elseif (strlen($deathAlt) == 0) {
            $this->deathYear = '';
            $this->deathDate = '';
        }
        return $this;
    }

    /**
     * Get birthAlt
     *
     * @return string
     */
    public function getBirthAlt()
    {
        $year = $this->birthYear;
        $date = $this->birthDate;
        if ($date != "") {
            $date = $date . "/";

        }
        return $date . $year;
    }

    /**
     * Get deathAlt
     *
     * @return string
     */
    public function getDeathAlt()
    {
        $year = $this->deathYear;
        $date = $this->deathDate;
        if ($date != "") {
            $date .= "/";

        }
        return $date . $year;
    }

    /**
     * Set death
     *
     * @param \DateTime $death
     * @return Person
     */
    public function setDeath($death)
    {
        $this->death = $death;

        return $this;
    }

    /**
     * Get death
     *
     * @return \DateTime
     */
    public function getDeath()
    {
        $year = $this->deathYear;
        $date = $this->deathDate;
        if ($date != "") {
            $date .= "/";

        }
        return $date . $year;
    }

    /**
     * @return integer
     */
    public function getAge()
    {
        if ($this->birth) {
            $byear = $this->birth->format('Y');
        } elseif ($this->birthYear) {
            $byear = $this->birthYear;
        } else return null;

        if ($this->death) {
            $dyear = $this->death->format('Y');
        } elseif ($this->deathYear) {
            $dyear = $this->deathYear;
        } else return null;


        $interval = $dyear - $byear;
        if ($interval > 120) $interval = null;

        return $interval;
    }

    /**
     * @return string
     */
    public function getDates()
    {
        $dates = "";
        if (($this->birthYear)) {
            $dates = $this->birthYear;
        }

        if (($this->deathYear)) {
            $dates .= " - " . $this->deathYear;
        }

        return $dates;
    }

src/FamilyTreeBundle/Form/ChangesType.php
<?php

namespace FamilyTreeBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class ChangesType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('author')
            ->add('comment')
            ->add('region')
        ;
    }
    
    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'FamilyTreeBundle\Entity\Changes'
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'sandello_familytreebundle_changes';
    }
}

src/FamilyTreeBundle/Resources/views/Changes/edit.html.twig
{% extends 'TreeBundle::base.html.twig' %}

{% block container -%}
    <h1>Changes edit</h1>
    {{ form(edit_form) }}
<ul class="record_actions">
    <li>
        <a href="{{ path('changes') }}">
            Back to the list
        </a>
    </li>
    <li>{{ form(delete_form) }}</li>
</ul>
{% endblock %}

src/FamilyTreeBundle/Resources/views/Changes/index.html.twig
{% extends 'TreeBundle::base.html.twig' %}

{% block container -%}
    <div class="col-md-12">
        <div class="profile">
            <h2>{{ 'Changes list'|trans }}</h2>
            <table class="records_list table table-striped table-hover">
                <thead>
                <tr>
                    <th>{{ 'Id'|trans }}</th>
                    <th style="width: 80px;">{{ 'Date'|trans }}</th>
                    <th style="width: 180px;">{{ 'Author'|trans }}</th>
                    <th style="width: 180px;">{{ 'Person'|trans }}</th>
                    <th>{{ 'Comment'|trans }}</th>
                    <th>{{ 'Region'|trans }}</th>
                    <th style="width: 100px;">{{ 'Field'|trans }}</th>
                    <th>{{ 'Current'|trans }}</th>
                    <th>{{ 'Suggested'|trans }}</th>
                    <th style="width: 60px;">{{ 'Actions'|trans }}</th>
                </tr>
                </thead>
                <tbody>
                {% for entity in entities %}
                    <tr>
                        <td>
                            <a href="{{ path('changes_show', { 'id': entity.id }) }}">{{ entity.id }}</a>
                        </td>
                        <td>
                            {{ entity.pdate|date('d/m/Y') }}
                        </td>
                        <td>
                            {{ entity.author }}
                        </td>
                        <td>
                            <a href="{{ path('changes_show', { 'id': entity.id }) }}">{{ entity.person.names }}</a>
                        </td>
                        <td>
                            {{ entity.comment }}
                        </td>
                        <td>
                            {{ entity.region }}
                        </td>
                        <td>
                            {% for change in entity.changes %}
                                <p><b>{{ change.field }}</b></p>
                                <hr>
                            {% endfor %}
                        </td>
                        <td class="change">
                            {% for change in entity.changes %}
                                {% if attribute( entity.person, change.field ).timestamp is defined %}
                                    {{ attribute( entity.person, change.field )|date('Y-m-d') }}
                                {% else %}
                                    {% if change.field == "avatar" %}
                                        <img src="{{ attribute( entity.person, change.field ) }}" class="img-responsive">
                                    {% else %}
                                        <p>{{ attribute( entity.person, change.field) }}&nbsp;</p>
                                    {% endif %}
                                {% endif %}
                                <hr>
                            {% endfor %}
                        </td>
                        <td class="change">
                            {% for change in entity.changes %}
                                <p>
                                    {{ change.value | raw }}&nbsp;
                                </p>
                                <hr>
                            {% endfor %}
                        </td>
                        <td>
                            <form method="POST" action="{{ path('accept',{'id':entity.id}) }}">
                                <button class="accept"></button>
                            </form>

                            <form method="POST" action="{{ path('decline',{'id':entity.id}) }}">
                                <button class="decline"></button>
                            </form>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <script src="/js/jquery.colorbox.js" type="text/javascript"></script>
    <script>
        $(document).ready(function () {
            $(".accept").click(function (event) {
                if (confirm("{{ 'Are you sure you want to apply this change to database?'|trans }}")) {

                } else {
                    event.preventDefault();
                }
            });
            $(".decline").click(function (event) {
                if (confirm("{{ 'Are you sure you want to delete this suggestion?'|trans }}")) {

                } else {
                    event.preventDefault();
                }
            });

            $(".cbox").click(function () {
                $(this).colorbox(
                        {
                            href: $(this).attr('src'),
                            width: "75%",
                            height: "75%",
                            photo: "true",
                            title: function () {
                                var download = "<a href=\"" + $(this).attr('src') + "\" download class=\"btn btn-default\">{{ 'Download' | trans }}</a>";
                                return download;
                            }
                        });
            });
        });
    </script>
{% endblock %}

src/FamilyTreeBundle/Resources/views/Changes/new.html.twig
{% extends 'TreeBundle::base.html.twig' %}

{% block container -%}
    <h1>Changes creation</h1>

    {{ form(form) }}

        <ul class="record_actions">
    <li>
        <a href="{{ path('changes') }}">
            Back to the list
        </a>
    </li>
</ul>
{% endblock %}

src/FamilyTreeBundle/Resources/views/Changes/show.html.twig
{% extends 'TreeBundle::base.html.twig' %}

{% block body -%}
<div class="col-md-6 fixed" id="profile-edit">	
	<div class="profile edit">
		<div class="profile-avatar" title="Change the avatar">
			{% if changes['avatar']|length > 0 %}{{ changes['avatar'] | raw }}{% else %}<img alt="Avatar" src="{{ person.avatar }}" class="img-responsive profile-photo ">{% endif %}
		</div>
		<div class="profile-info">
			<ul>
				<li class="str_edit"><span class="change">{{ changes['lastName'] }}</span>{% if changes['lastName']|length > 0 %}<span class="old"> ({{ person.lastName}})</span>{% else %}{{ person.lastName}}{% endif %}</li>
				<li class="str_edit"><span class="change">{{ changes['firstName'] }}</span>{% if changes['firstName']|length > 0 %}<span class="old"> ({{ person.firstName}})</span>{% else %}{{ person.firstName}}{% endif %}</li>
				<li class="str_edit"><span class="change">{{ changes['nickname'] }}</span>{% if changes['nickname']|length > 0 %}<span class="old"> ({{ person.nickname}})</span>{% else %}{{ person.nickname}}{% endif %}</li>
			</ul>
		</div>
		<div class="action-buttons">
			<a href="{{ path('person_show',{'id': person.id}) }}"><button type="button" class="btn">{{ 'Show profile'|trans }}</button></a>
			<form method="POST" action="{{ path('accept',{'id':entity.id}) }}">
				<button>{{ 'Accept'|trans }}</button>
			</form>
			<form method="POST" action="{{ path('decline',{'id':entity.id}) }}">
				<button>{{ 'Delete'|trans }}</button>
			</form>
		</div>
		<div class="clearfix"></div>
	</div>

	<div class="profile">
		<table class="table profile-details">
			<tr>
				<td class="tlabel">{{ 'Id'|trans }}:</td>
				<td>{{person.id}}</td>
			</tr>
			<tr>
				<td class="tlabel">{{ 'Sex'|trans }}:</td>
				<td><span class="change">{% if changes['sex']|length > 0 %}{% if changes['sex'] == 1 %}{{ 'Male'|trans }}{% else %}{{ 'Female'|trans }}{% endif %}{% endif %}</span>{% if changes['sex']|length > 0 %}<span class="old"> ({% if person.sex == 1 %}{{ 'Male'|trans }}{% else %}{{ 'Female'|trans }}{% endif %})</span>{% else %}{% if person.sex == 1 %}{{ 'Male'|trans }}{% else %}{{ 'Female'|trans }}{% endif %}{% endif %}</td>
				
			</tr>
			<tr>
				<td class="tlabel">{{ 'Birth'|trans }}:</td>
				<td><span class="change">{% if changes['birth']|length > 0 %}{{ changes['birth']|date('d/m/Y') }}{% endif %}</span>{% if changes['birth']|length > 0 %}<span class="old"> {% if person.birth|length > 0 %}({{ person.birth|date('d/m/Y') }}){% endif %}</span>{% else %}{{ person.birth|date('d/m/Y') }}{% endif %}</td>
			</tr>
			<tr>
				<td class="tlabel">{{ 'Birth place'|trans }}:</td>
				<td><span class="change">{{ changes['birthPlace'] }}</span>{% if changes['birthPlace']|length > 0 %}<span class="old"> ({{ person.birthPlace}})</span>{% else %}{{ person.birthPlace}}{% endif %}</td>
			</tr>
			<tr>
				<td class="tlabel">{{ 'Occupation'|trans }}:</td>
				<td><span class="change">{{ changes['occupation'] }}</span>{% if changes['occupation']|length > 0 %}<span class="old"> ({{ person.occupation}})</span>{% else %}{{ person.occupation}}{% endif %}</td>
			</tr>
			<tr>
				<td class="tlabel">{{ 'Death'|trans }}:</td>
				<td><span class="change">{% if changes['death']|length > 0 %}{{ changes['death']|date('d/m/Y') }}{% endif %}</span>{% if person.death|length > 0 %}{{ person.death|date('d/m/Y') }}{% endif %}</td>
			</tr>
			<tr>
				<td class="tlabel">{{ 'Place of death'|trans }}:</td>
				<td><span class="change">{{ changes['deathPlace'] }}</span>{% if changes['deathPlace']|length > 0 %}<span class="old"> ({{ person.deathPlace}})</span>{% else %}{{ person.deathPlace}}{% endif %}</td>
			</tr>
			<tr>
				<td class="tlabel">{{ 'Note'|trans }}:</td>
				<td class="area_edit" ><span class="change">{{ changes['note'] }}</span>{% if changes['note']|length > 0 %}<span class="old"> ({{ person.note}})</span>{% else %}{{ person.note}}{% endif %}</td>
			</tr>
			<tr>
				<td class="tlabel">{{ 'Private note'|trans }}:</td>
				<td class="area_edit">{{ person.privateNote }}</td>
			</tr>
		</table>
	</div>
	<div class="profile">
		<table class="table profile-details">
			<tr>
				<td class="tlabel">{{ entity.author }}:</td>
				<td class="area_edit">{{ entity.comment }}</td>
			</tr>
		</table>
	</div>
</div>
	
<div class="col-md-6 relfixed">
	{#{% for change in entity.changes %}
	<p>
		<b>{{ change.field }}</b><br/>
		{% if attribute( entity.person, change.field ).timestamp is defined %}
		{{ attribute( entity.person, change.field )|date('Y-m-d') }} => {{ change.value }}
		{% else %}
		{{ attribute( entity.person, change.field ) }} => {{ change.value }}
		{% endif %}
	</p>
	{% endfor %}#}

	<div class="parents profile">
			<h2>{{ 'Parents'|trans }}</h2>
			{% for parent in person.parents %}
			<div class="relative {% if parent.id in changes['parents_remove'] %}remove{% endif %}" id="{{ parent.id }}" >
				<div class="photo">
					<a href="{{ path('person_show',{ 'id':parent.id }) }}">
						<img src="{{ parent.avatar| apply_filter('relative')}}"/>
					</a>
				</div>
				<div class="name">
					<a href="{{ path('person_show',{ 'id':parent.id }) }}">
						<span>{{ parent.lastName }}</span><br>
						<span>{{ parent.firstName }}</span><br>
						<span>{{ parent.nickname }}</span>
					</a>
				</div>
				<div class="date">
					{{ parent.dates }}
				</div>
				<button class="remove-revative">X</button>
			</div>
			{% endfor %}
			<div class="clearfix"></div>
	</div>
	
	<div class="couses profile">
		<h2>{{'Spouses'|trans}}</h2>
			{% for couse in person.marriages %}
			<div class="relative parent {% if couse.id in changes['couse_remove'] %}remove{% endif %}" id="{{ couse.id }}" data-child="{% for child in couse.children %}{% if loop.index> 1 %},{% endif %}{{ child.id }}{% endfor %}">
				<div class="photo">
					<a href="{{ path('person_show',{'id':couse.id}) }}" >
						<img src="{{ couse.avatar| apply_filter('relative') }}"/>
					</a>
				</div>
				<div class="name">
					<a href="{{ path('person_show',{'id':couse.id}) }}">
						<span>{{couse.lastName}}</span><br>
						<span>{{couse.firstName}}</span><br>
						<span>{{couse.nickname}}</span>
					</a>
				</div>
				<div class="date">
					{{ couse.dates }}
				</div>
				<button class="remove-revative">X</button>
			</div>
			{% endfor %}
			<div class="clearfix"></div>
	</div>

	<div class="children profile">
		<h2>{{'Children'|trans}}</h2>
		{% for child in person.children %}
			<div class="relative child {% if child.id in changes['child_remove'] %}remove{% endif %}" id="{{ child.id }}" >
				<div class="photo">
					<a href="{{ path('person_show',{'id':child.id}) }}">
						<img src="{{ child.avatar| apply_filter('relative') }}"/>
					</a>
				</div>
				<div class="name">
					<a href="{{ path('person_show',{'id':child.id}) }}" data-parent="{% for parent in child.parents %}{% if parent.id != entity.id %}{{ parent.id }}{% endif %}{% endfor %}">
						<span>{{ child.lastName }}</span><br>
						<span>{{ child.firstName }}</span><br>
						<span>{{ child.nickname }}</span>
					</a>
				</div>
				<div class="date">
					{{ child.dates }}
				</div>
				<button class="remove-revative">X</button>
			</div>
		{% endfor %}
		<div class="clearfix"></div>
	</div>

	<div class="bro profile">
		<h2>{{'Brothers and sisters'|trans}}</h2>
		{% for bro in person.brotherhood %}
			<div class="relative {% if bro.id in changes['bro_remove'] %}remove{% endif %}" id="{{ bro.id }}">
				<div class="photo">
					<a href="{{ path('person_show',{'id':bro.id}) }}">
						<img src="{{ bro.avatar| apply_filter('relative') }}"/>
					</a>
				</div>
				<div class="name">
					<a href="{{ path('person_show',{'id':bro.id}) }}">
						<span>{{ bro.lastName }}</span><br>
						<span>{{ bro.firstName }}</span><br>
						<span>{{ bro.nickname }}</span>
					</a>
				</div>
				<div class="date">
					{{ bro.dates }}
				</div>
				<button class="remove-revative">X</button>
			</div>
		{% endfor %}
		<div class="clearfix"></div>
	</div>
</div>
{% endblock %}