src/FamilyTreeBundle/Entity/Message.php
<?php

namespace FamilyTreeBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\UploadedFile;

/**
 * Message
 *
 * @ORM\Table()
 * @ORM\Entity
 */
class Message
{
    /**
     * @var integer
     *
     * @ORM\Id
     * @ORM\Column(name="id", type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     * @ORM\Column(name="author", type="string", nullable=true)
     */
    private $author;

    /**
     * @var string
     * @ORM\Column(name="email", type="string", nullable=true)
     */
    private $email;

    /**
     * @var string
     * @ORM\Column(name="message", type="string", nullable=true)
     */
    private $message;

    /**
     * @var \DateTime
     * @ORM\Column(name="post_date", type="date", nullable=true)
     */
    private $pdate;

    /**
     * @Assert\Image(maxSize="10000000")
     */
    public $file;

    /**
     * @var string
     *
     * @ORM\Column(name="filePath", type="string", length=255, nullable=true)
     */
    private $filePath;


    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set author
     *
     * @param string $author
     * @return Message
     */
    public function setAuthor($author)
    {
        $this->author = $author;

        return $this;
    }

    /**
     * Get author
     *
     * @return string
     */
    public function getAuthor()
    {
        return $this->author;
    }

    /**
     * Set email
     *
     * @param string $email
     * @return Message
     */
    public function setEmail($email)
    {
        $this->email = $email;

        return $this;
    }

    /**
     * Get email
     *
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Set message
     *
     * @param string $message
     * @return Message
     */
    public function setMessage($message)
    {
        $this->message = $message;

        return $this;
    }

    /**
     * Get message
     *
     * @return string
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * Set pdate
     *
     * @param \DateTime $pdate
     * @return Message
     */
    public function setPdate($pdate)
    {
        $this->pdate = $pdate;

        return $this;
    }

    /**
     * Get pdate
     *
     * @return \DateTime
     */
    public function getPdate()
    {
        return $this->pdate;
    }

    /**
     * Set filePath
     *
     * @param string $filePath
     * @return Message
     */
    public function setFilePath($filePath)
    {
        $this->filePath = $filePath;

        return $this;
    }

    /**
     * Get filePath
     *
     * @return string
     */
    public function getFilePath()
    {
        return $this->filePath;
    }

    public function getFileview()
    {
        if ($this->filePath != null) {
            $allowed_image = array("jpg", "png", "gif", "bmp", "jpeg");

            if ((in_array(strtolower(substr($this->filePath, -3)), $allowed_image)) || (in_array(strtolower(substr($this->filePath, -4)), $allowed_image))) {
                return "<br><a href=\"/" . $this->getWebPath() . "\" download><img src=\"/" . $this->getWebPath() . "\" class=\"img-responsive profile-photo cbox\"></a>";
            } else {
                return "<br><a href=\"/" . $this->getWebPath() . "\" download>file</a>";
            }
        }
    }

    public function upload()
    {
        if (null === $this->getFile()) {
            return;
        }

        $filename = time() . "." . $this->getFile()->guessExtension();

        $this->getFile()->move(
            $this->getUploadRootDir(),
            $filename
        );

        $this->filePath = $filename;

        $this->file = null;
    }

    public function getAbsolutePath()
    {
        return null === $this->filePath
            ? null
            : $this->getUploadRootDir() . '/' . $this->filePath;
    }

    public function getWebPath()
    {
        return null === $this->filePath
            ? null
            : $this->getUploadDir() . '/' . $this->filePath;
    }

    protected function getUploadRootDir()
    {
        return __DIR__ . '/../../../web/' . $this->getUploadDir();
    }

    protected function getUploadDir()
    {
        return 'uploads/messages';
    }

    /**
     * Sets file.
     *
     * @param UploadedFile $file
     */
    public function setFile(UploadedFile $file = null)
    {
        $this->file = $file;
    }

    /**
     * Get file.
     *
     * @return UploadedFile
     */
    public function getFile()
    {
        return $this->file;
    }

}

src/FamilyTreeBundle/Entity/Person.php
<?php

namespace FamilyTreeBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Person
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="FamilyTreeBundle\Entity\Repository\PersonRepository")
 */
class Person
{
    public function returnDate()
    {
        return $this->birthYear;
    }

    public function getNames()
    {
        $lname = $this->lastName ? $this->lastName . ' ' : '';
        $fname = $this->firstName ? $this->firstName . ' ' : '';
        //.($this->birth||$this->death?'(':'').($this->birth?$this->birth->format('Y'):'unknown').($this->death ? ' - ':'').($this->death?$this->death->format('Y'):'unknown').($this->birth||$this->death?')':'')
        $fname = explode(" ", $fname);
        return $lname . $fname[0];
    }

    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="firstName", type="string", length=255)
     */
    private $firstName;

    /**
     * @var string
     *
     * @ORM\Column(name="lastName", type="string", length=255)
     */
    private $lastName;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="birth", type="date", nullable=true)
     */
    private $birth;

    /**
     * @var string
     *
     * @ORM\Column(name="birthYear", type="string")
     */
    private $birthYear;

    /**
     * @var string
     *
     * @ORM\Column(name="birthDate", type="string", nullable=true)
     */
    private $birthDate;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="death", type="date", nullable=true)
     */
    private $death;

    /**
     * @var string
     *
     * @ORM\Column(name="deathYear", type="string")
     */
    private $deathYear;

    /**
     * @var string
     *
     * @ORM\Column(name="deathDate", type="string", nullable=true)
     */
    private $deathDate;

    /**
     * @var string
     *
     * @ORM\Column(name="occupation", type="string", length=255, nullable=true)
     */
    private $occupation;


    /**
     * @var string
     *
     * @ORM\Column(name="birthPlace", type="string", length=255, nullable=true)
     */
    private $birthPlace;

    /**
     * @var string
     *
     * @ORM\Column(name="deathPlace", type="string", length=255, nullable=true)
     */
    private $deathPlace;

    /**
     * @var string
     *
     * @ORM\Column(name="note", type="text", nullable=true)
     */
    private $note;

    /**
     * @var string
     *
     * @ORM\Column(name="privateNote", type="text", nullable=true)
     */
    private $privateNote;

    /**
     * @var string
     * @ORM\ManyToOne(targetEntity="GalleryBundle\Entity\File")
     */
    private $avatarFile;


    /**
     * @ORM\Column(name="avatar_url", type="string", nullable=true)
     */
    private $avatarUrl;

    /**
     * @ORM\ManyToMany(targetEntity="Person", mappedBy="children", cascade={"persist"})
     * @ORM\OrderBy({"sex" = "DESC"})
     */
    private $parents;

    /**
     * @ORM\OneToMany(targetEntity="Marriage", mappedBy="person")
     */
    private $marriages;

    /**
     * @ORM\ManyToMany(targetEntity="Person", inversedBy="parents", cascade={"persist"})
     * @ORM\JoinTable(name="Children",
     * joinColumns={@ORM\JoinColumn(name="child", referencedColumnName="id")},
     * inverseJoinColumns={@ORM\JoinColumn(name="parent", referencedColumnName="id")}
     * )
     * @ORM\OrderBy({"birthYear" = "ASC"})
     */
    private $children;

    /**
     * @ORM\ManyToMany(targetEntity="Person", cascade={"persist"})
     * @ORM\JoinTable(name="Brotherhood",
     * joinColumns={@ORM\JoinColumn(name="person_1", referencedColumnName="id")},
     * inverseJoinColumns={@ORM\JoinColumn(name="person_2", referencedColumnName="id")}
     * )
     * @ORM\OrderBy({"birthYear" = "ASC"})
     */
    private $brotherhood;

    /**
     * @var boolean
     *
     * @ORM\Column(name="sex", type="boolean", nullable=true)
     */
    private $sex;

    /**
     * @var string
     *
     * @ORM\Column(name="nickname", type="string", length=255, nullable=true)
     */
    private $nickname;

    /**
     * @var string
     *
     * @ORM\Column(name="is_published", type="boolean", options={"default" = true})
     */
    private $isPublished;

    /**
     * @ORM\OneToMany(targetEntity="GalleryBundle\Entity\File", mappedBy="owner", cascade={"remove","persist"})
     */
    private $files;

    /**
     * @ORM\OneToMany(targetEntity="Changes", mappedBy="person", cascade={"remove","persist"})
     */
    private $changes;

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->marriages = new \Doctrine\Common\Collections\ArrayCollection();
        $this->children = new \Doctrine\Common\Collections\ArrayCollection();
        $this->parents = new \Doctrine\Common\Collections\ArrayCollection();
        $this->brotherhood = new \Doctrine\Common\Collections\ArrayCollection();
        $this->isPublished = true;
    }


    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set firstName
     *
     * @param string $firstName
     * @return Person
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Set firstName
     *
     * @param string $firstName
     * @return Person
     */
    public function setFirstName($firstName)
    {
        $this->firstName = strtolower($firstName);

        return $this;
    }

    /**
     * Get firstName
     *
     * @return string
     */
    public function getFirstName()
    {
        return $this->firstName;
    }

    /**
     * Set lastName
     *
     * @param string $lastName
     * @return Person
     */
    public function setLastName($lastName)
    {
        $this->lastName = strtolower($lastName);

        return $this;
    }

    /**
     * Get lastName
     *
     * @return string
     */
    public function getLastName()
    {
        return $this->lastName;
    }

    /**
     * Set birth
     *
     * @param \DateTime $birth
     * @return Person
     */
    public function setBirth($birth)
    {
        $this->birth = $birth;

        return $this;
    }

    /**
     * Get birth
     *
     * @return \DateTime
     */
    public function getBirth()
    {
        $year = $this->birthYear;
        $date = $this->birthDate;
        if ($date != "") {
            $date = $date . "/";
        }
        return $date . $year;
    }


    /**
     * Set birthAlt
     *
     * @param string $birthAlt
     * @return Person
     */
    public function setBirthAlt($birthAlt)
    {
        if (strlen($birthAlt) == 4) {
            $this->birthYear = $birthAlt;
            $this->birthDate = '';
        } elseif (strlen($birthAlt) == 10) {
            $delimeter = preg_replace("/[0-9\s]/", "", $birthAlt);
            $datearr = explode($delimeter[0], $birthAlt);
            $birthAlt = $datearr[2] . "-" . $datearr[1] . "-" . $datearr[0];
            $this->birthYear = $datearr[2];
            $this->birthDate = $datearr[0] . "/" . $datearr[1];
        } elseif (strlen($birthAlt) == 0) {
            $this->birthYear = '';
            $this->birthDate = '';
        }
        return $this;
    }

    /**
     * Set deathAlt
     *
     * @param string $deathAlt
     * @return Person
     */
    public function setDeathAlt($deathAlt)
    {

        if (strlen($deathAlt) == 4) {
            $this->deathYear = $deathAlt;
            $this->deathDate = '';

        } elseif (strlen($deathAlt) == 10) {
            $delimeter = preg_replace("/[0-9\s]/", "", $deathAlt);
            $datearr = explode($delimeter[0], $deathAlt);
            $deathAlt = $datearr[2] . "-" . $datearr[1] . "-" . $datearr[0];
            $this->deathYear = $datearr[2];
            $this->deathDate = $datearr[0] . "/" . $datearr[1];
        } elseif (strlen($deathAlt) == 0) {
            $this->deathYear = '';
            $this->deathDate = '';
        }
        return $this;
    }

    /**
     * Get birthAlt
     *
     * @return string
     */
    public function getBirthAlt()
    {
        $year = $this->birthYear;
        $date = $this->birthDate;
        if ($date != "") {
            $date = $date . "/";

        }
        return $date . $year;
    }

    /**
     * Get deathAlt
     *
     * @return string
     */
    public function getDeathAlt()
    {
        $year = $this->deathYear;
        $date = $this->deathDate;
        if ($date != "") {
            $date .= "/";

        }
        return $date . $year;
    }

    /**
     * Set death
     *
     * @param \DateTime $death
     * @return Person
     */
    public function setDeath($death)
    {
        $this->death = $death;

        return $this;
    }

    /**
     * Get death
     *
     * @return \DateTime
     */
    public function getDeath()
    {
        $year = $this->deathYear;
        $date = $this->deathDate;
        if ($date != "") {
            $date .= "/";

        }
        return $date . $year;
    }

    /**
     * @return integer
     */
    public function getAge()
    {
        if ($this->birth) {
            $byear = $this->birth->format('Y');
        } elseif ($this->birthYear) {
            $byear = $this->birthYear;
        } else return null;

        if ($this->death) {
            $dyear = $this->death->format('Y');
        } elseif ($this->deathYear) {
            $dyear = $this->deathYear;
        } else return null;


        $interval = $dyear - $byear;
        if ($interval > 120) $interval = null;

        return $interval;
    }

    /**
     * @return string
     */
    public function getDates()
    {
        $dates = "";
        if (($this->birthYear)) {
            $dates = $this->birthYear;
        }

        if (($this->deathYear)) {
            $dates .= " - " . $this->deathYear;
        }

        return $dates;
    }

src/FamilyTreeBundle/Resources/views/Admin/compare.html.twig
{% extends 'TreeBundle::base.html.twig' %}

{% block container -%}
    <div class="row" style="margin: 0;">
        {% for person in persons %}
            <div class="col-md-6">
                <div class="profile">
                    <div class="profile-avatar">
                        <img src="{{ person.avatarUrl | apply_filter('search') }}" class="img-responsive profile-photo ">
                    </div>
                    <div class="profile-info">
                        <ul>
                            <li data-bind="surname">{{ person.lastName|title }}</li>
                            <li data-bind="name">
                                {% set firstName = person.firstName|split(' ', 2) %}
                                <span class="prime">{{ firstName[0] | title }}</span>
                                {% if firstName[1] is defined %}
                                    <span class="secondary">{{ firstName[1] | title }}</span>
                                {% endif %}
                            </li>
                            <li data-bind="nickname"><span class="secondary">{{ person.nickname|title }}</span></li>
                        </ul>
                    </div>
                    <div class="action-buttons">
                        <a href="{{ path('person_show_tree',{'id': person.id}) }}" class="">
                            <button type="button" class="tree">{{ 'Tree'|trans }}</button>
                        </a>
                        <a href="{{ path('person_show', { 'id': person.id }) }}">
                            <button type="button" class="edit edit_tooltip" data-original-title="Another tooltip">{{ 'Show profile'|trans }}</button>
                        </a>
                        <a href="{{ path('person_edit', { 'id': person.id }) }}">
                            <button type="button" class="edit edit_tooltip" data-original-title="Another tooltip">{{ 'Edit person'|trans }}</button>
                        </a>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
        {% endfor %}
    </div>
    <div class="row" style="margin: 0;">
        {% for person in persons %}
            <div class="col-md-6">
                <div class="profile" style="margin-top: 35px;">
                    <table class="table profile-details">
                        <tr>
                            <td class="tlabel">{{ 'Id'|trans }}:</td>
                            <td class="">{{ person.id }}</td>
                        </tr>
                        <tr>
                            <td class="tlabel">{{ 'Gender'|trans }}:</td>
                            <td class="select_edit">{% if person.sex %}{{ 'Male'|trans }}{% else %}{{ 'Female'|trans }}{% endif %}</td>
                        </tr>
                        <tr>
                            <td class="tlabel">{{ 'Birth'|trans }}:</td>
                            <td class="str_edit">{{ person.birth }}</td>
                        </tr>
                        <tr>
                            <td class="tlabel">{{ 'Birth place'|trans }}:</td>
                            <td class="str_edit">{{ person.birthPlace|title }}</td>
                        </tr>
                        <tr>
                            <td class="tlabel">{{ 'Occupation'|trans }}:</td>
                            <td class="str_edit">{{ person.occupation|title }}</td>
                        </tr>
                        <tr>
                            <td class="tlabel">{{ 'Death'|trans }}:</td>
                            <td class="str_edit">{{ person.death }}</td>
                        </tr>
                        <tr>
                            <td class="tlabel">{{ 'Place of death'|trans }}:</td>
                            <td class="str_edit">{{ person.deathPlace }}</td>
                        </tr>
                        <tr>
                            <td class="tlabel">{{ 'Year of birth'|trans }}:</td>
                            <td class="str_edit">{{ person.birthYear }}</td>
                        </tr>
                        <tr>
                            <td class="tlabel">{{ 'Year of death'|trans }}:</td>
                            <td class="str_edit">{{ person.deathYear }}</td>
                        </tr>
                        <tr>
                            <td class="tlabel">{{ 'Age'|trans }}:</td>
                            <td class="">{{ person.age }}</td>
                        </tr>
                        <tr>
                            <td class="tlabel">{{ 'NOTE'|trans }}:</td>
                            <td class="area_edit">{{ person.note|title }}</td>
                        </tr>
                        <tr>
                            <td class="tlabel">{{ 'Private note'|trans }}:</td>
                            <td class="area_edit">{{ person.privateNote|raw }}</td>
                        </tr>
                    </table>
                </div>
            </div>
        {% endfor %}
    </div>
    <div class="row" style="margin: 0;">
        {% for person in persons %}
            <div class="col-md-6">
                <div class="relatives block">
                    <h2>{{ 'Parents'|trans }}</h2>
                    <div class="relative_list">
                        {% for parent in person.parents %}
                            <div class="relative">
                                <div class="photo">
                                    <a href="{{ path('person_show',{ 'id':parent.id }) }}">
                                        <img src="{{ parent.avatarUrl | apply_filter('relative') }}"/>
                                    </a>
                                </div>
                                <div class="name">
                                    <a href="{{ path('person_show',{ 'id':parent.id }) }}">
                                        <span>{{ parent.lastName|title }}</span><br>
                                    <span>
                                        {% set firstName = parent.firstName|split(' ', 2) %}
                                        <span class="prime">{{ attribute(firstName, 0)|title }}</span>
                                        {% if firstName[1] is defined %}
                                            <span class="secondary">{{ firstName[1] | title }}</span>
                                        {% endif %}
                                    </span>
                                        <br>
                                        <span class="secondary">{{ parent.nickname|title }}</span>
                                    </a>
                                    <div class="date">{{ parent.dates }}</div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    <div class="row" style="margin: 0;">
        {% for person in persons %}
            <div class="col-md-6">
                <div class="relatives block">
                    <h2>{{ 'Spouses'|trans }}</h2>
                    <div class="relative_list">
                        {% for marriage in person.marriages %}
                            {% set spouse = marriage.spouse %}
                            <div class="relative parent">
                                <div class="photo">
                                    <a href="{{ path('person_show',{'id':spouse.id}) }}">
                                        <img src="{{ spouse.avatarUrl | apply_filter('relative') }}"/>
                                    </a>
                                </div>
                                <div class="name">
                                    <a href="{{ path('person_show',{'id':spouse.id}) }}">
                                        <span>{{ spouse.lastName|title }}</span><br>
                                    <span>
                                        {% set firstName = spouse.firstName|split(' ', 2) %}
                                        <span class="prime">{{ attribute(firstName, 0) | title }}</span>
                                        {% if firstName[1] is defined %}
                                            <span class="secondary">{{ firstName[1] | title }}</span>
                                        {% endif %}
                                    </span>
                                        <br>
                                        <span class="secondary">{{ spouse.nickname|title }}</span>
                                    </a>

                                    <div class="date">
                                        <span>{{ spouse.dates }}</span>
                                    </div>
                                </div>
                                {% if marriage.marriageDate|length > 0 %}
                                    <div class="mdate">
                                        <span class="secondary">{{ 'Married'|trans }}:</span> {{ marriage.marriageDate }}
                                    </div>
                                {% endif %}
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    <div class="row" style="margin: 0;">
        {% for person in persons %}
            <div class="col-md-6">
                <div class="relatives block">
                    <h2>{{ 'Children'|trans }}</h2>
                    <div class="relative_list">
                        {% for child in person.children %}
                            <div class="relative child" id="{{ child.id }}">
                                <div class="photo">
                                    <a href="{{ path('person_show',{'id':child.id}) }}">
                                        <img src="{{ child.avatarUrl | apply_filter('relative') }}"/>
                                    </a>
                                </div>
                                <div class="name">
                                    <a href="{{ path('person_show',{'id':child.id}) }}">
                                        <span>{{ child.lastName|title }}</span><br>
                                    <span>
                                        {% set firstName = child.firstName|split(' ', 2) %}
                                        <span class="prime">{{ attribute(firstName, 0)|title }}</span>
                                        {% if firstName[1] is defined %}
                                            <span class="secondary">{{ firstName[1] | title }}</span>
                                        {% endif %}
                                    </span>
                                        <br>
                                        <span class="secondary">{{ child.nickname|title }}</span>
                                    </a>

                                    <div class="date">{{ child.dates }}</div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    <div class="row" style="margin: 0;">
        {% for person in persons %}
            <div class="col-md-6">
                <div class="relatives block">
                    <h2>{{ 'Brothers and sisters'|trans }}</h2>
                    <div class="relative_list">
                        {% for bro in person.brotherhood %}
                            <div class="relative" id="{{ bro.id }}">
                                <div class="photo">
                                    <a href="{{ path('person_show',{'id':bro.id}) }}">
                                        <img src="{{ bro.avatarUrl | apply_filter('relative') }}"/>
                                    </a>
                                </div>
                                <div class="name">
                                    <a href="{{ path('person_show',{'id':bro.id}) }}">
                                        <span>{{ bro.lastName|title }}</span><br>
                                    <span>
                                        {% set firstName = bro.firstName|split(' ', 2) %}
                                        <span class="prime">{{ attribute(firstName, 0)|title }}</span>
                                        {% if firstName[1] is defined %}
                                            <span class="secondary">{{ firstName[1] | title }}</span>
                                        {% endif %}
                                    </span>
                                        <span class="secondary">{{ bro.nickname|title }}</span>
                                    </a>
                                    <div class="date">{{ bro.dates }}</div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

src/FamilyTreeBundle/Resources/views/Admin/messages.html.twig
{% extends 'TreeBundle::base.html.twig' %}

{% block container -%}
	<div class="title"><h1>{{ 'Message list'|trans }}</h1></div>
	<table class="records_list table table-striped table-hover">
		<thead>
			<tr>
				<th style="width: 30px;">{{ 'Id'|trans }}</th>
				<th style="width: 80px;">{{ 'Date'|trans }}</th>
				<th style="width: 180px;">{{ 'Author'|trans }}</th>
				<th style="width: 180px;">{{ 'Email'|trans }}</th>
				<th>{{ 'Message'|trans }}</th>
				<th style="width: 60px;">{{ 'Actions'|trans }}</th>
			</tr>
		</thead>
		<tbody>
		{% for entity in entities %}
			<tr>
				<td>{{ entity.id }}</td>
				<td>{{ entity.pdate|date('d/m/Y') }}</td>
				<td>{{ entity.author }}</td>
				<td>{{ entity.email }}</td>
				<td class="message">{{ entity.message }} {{ entity.fileview | raw }}</td>
				<td>
					<form method="POST" action="{{ path('delete_message',{'id':entity.id}) }}">
						<button class="decline"></button>
					</form>
				</td>
			</tr>
		{% endfor %}
		</tbody>
	</table>
    <script src="/js/jquery.colorbox.js" type="text/javascript"></script>
    <script>
    $(document).ready(function(){
        $(".message").each(function()
        {
            var descr = $(this).text();
            var persons = descr.match(/\@\d+/g);
            if (persons != null) {
                values = persons.join(",").replace(/\@/g, "");
                
                $.ajax({
                    url: "{{ path('search_person_by_id') }}",
                    type: "POST",
                    data: {query: values},
                    success: function(response){
                        var person = JSON.parse(response).suggestions[0];
                        
                        $(".message").each(function(){
                            var text = $(this).text();
                            var regexp = new RegExp('\\@'+person.id, 'g');
                            if (regexp.test(text) )
                            {
                                $(this).html(text.replace(regexp, '<b><a href="/person/' + person.id + '">' + person.value + '</a></b>'));
                            }
                        });
                    }
                });
            
            }
            return descr;
        });
        
        $(".cbox").click(function(){
			$(this).colorbox(
			{
				href: $(this).attr('src'),
				width:"75%", 
				height:"75%",
				photo: "true",
				title: function()
				{
				var download = "<a href=\"" + $(this).attr('src') + "\" download class=\"btn btn-default\">{{ 'Download' | trans }}</a>";
					return download;
				}
			});
		});
    });
    </script>
{% endblock %}